---
- hosts: localhost
  tasks:
    - name: Ensure destination directory exists
      file:
        path: /var/www/html
        state: directory
    - name: Copy index.html to web root
      copy:
        src: index.html
        dest: /var/www/html/index.html